services:
  grafana:
    labels:
      - traefik.http.routers.grafana.rule={{ if ne "${GRAFANA_DOMAIN}" "" }}Host(`{{ "${GRAFANA_DOMAIN}" }}`){{ else }}Host(`{{ "${DOMAIN}" }}`){{ end }}{{ if ne "${GRAFANA_PATH}" "" }}&& PathPrefix(`{{ "${GRAFANA_PATH}" }}`){{ end }}
      - traefik.http.routers.grafana.entrypoints=${TRAEFIK_ENTRYPOINTS:-http}
