services:
  grafana:
    labels:
      - traefik.http.routers.grafana.rule=Host(`${GRAFANA_DOMAIN:-${DOMAIN}}`) && PathPrefix(`${GRAFANA_PATH:-/grafana}`)
      - traefik.http.routers.grafana.entrypoints=${TRAEFIK_ENTRYPOINTS:-http,https}
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certResolver=${LETSENCRYPT_PROVIDER:-le}
