services:
  rocketchat:
    labels:
      - traefik.enable=true
      - traefik.http.services.svc-rocketchat.loadBalancer.healthcheck.path=/health
      - traefik.http.services.svc-rocketchat.loadBalancer.healthcheck.interval=10s
      - traefik.http.services.svc-rocketchat.loadBalancer.healthcheck.timeout=3s
      - traefik.http.routers.rocketchat.rule={{ if ne "${ROCKETCHAT_DOMAIN}" "" }}Host(`{{ "${ROCKETCHAT_DOMAIN}" }}`){{ else }}Host(`{{ "${DOMAIN}" }}`){{ end }}{{ if ne "${ROCKETCHAT_PATH}" "" }}&& PathPrefix(`{{ "${ROCKETCHAT_PATH}" }}`){{ end }}
      - traefik.http.routers.rocketchat.entryPoints=${ENTRYPOINTS:-http,https}
      - traefik.http.routers.rocketchat.service=svc-rocketchat
      - traefik.http.routers.rocketchat.tls.enable=true
      - traefik.http.routers.rocketchat.tls.certResolver=${LETSENCRYPT_PROVIDER:-le}
