services:
    rocketchat:
        labels:
            - traefik.enable=true
            - traefik.http.services.svc-rocketchat.loadBalancer.healthcheck.path=/health
            - traefik.http.services.svc-rocketchat.loadBalancer.healthcheck.interval=10s
            - traefik.http.services.svc-rocketchat.loadBalancer.healthcheck.timeout=3s
            - traefik.http.routers.rocketchat.rule={{ if eq (env "ROCKETCHAT_DOMAIN") "" }} Host(`{{ env "DOMAIN" }}`) && PathPrefix(`{{ env "ROCKETCHAT_PATH" }}`) {{ else }} Host(`{{ env "ROCKETCHAT_DOMAIN" }}`) {{ end }}
            - traefik.http.routers.rocketchat.entryPoint=${ENTRYPOINT:-http}
            - traefik.http.routers.rocketchat.service=svc-rocketchat
