services:
  traefik-init:
    command:
      - -c
      - |-
        set -e
        # quote 'eof' to prevent variable expansion
        rm -rf /traefik_config/* || true

        echo "ROCKETCHAT_BACKEND_SERVERS $$ROCKETCHAT_BACKEND_SERVERS"
        # append the server list to the services template
        for server in $(echo $$ROCKETCHAT_BACKEND_SERVERS | tr "," "\n" | tr -d " "); do
          echo "          - url: \"http://\$$server\"" >> /traefik_config/services.tpl
        done

        cat <<'EOF' > /traefik_config/http/dynamic.yml
        http:
          routers:
            rocketchat:
              entryPoints:
                - http
              service: rocketchat
              rule: Host(`{{ env "DOMAIN" }}`) && PathPrefix(`/`)
            grafana:
              entryPoints:
                - http
              service: grafana
              rule: |-
                {{ if eq (env "GRAFANA_DOMAIN") "" }}
                  Host(`{{ env "DOMAIN" }}`) && PathPrefix(`{{ env "GRAFANA_PATH" }}`)
                {{ else }}
                  Host(`{{ env "GRAFANA_DOMAIN" }}`)
                {{ end }}
        EOF

        cat /traefik_config/services.tpl >> /traefik_config/http/dynamic.yml
        cat /traefik_config/http/dynamic.yml
        echo "-------------------------"

        echo "files generated, keeping container alive to podman-compose detect it"
        tail -f /dev/null
    entrypoint: sh
    environment:
      ROCKETCHAT_BACKEND_SERVERS: ${ROCKETCHAT_BACKEND_SERVERS:-rocketchat:3000}
    image: docker.io/alpine:latest
    restart: "no"
    volumes:
      - traefik_config:/traefik_config:Z

  traefik:
    command:
      - --api.insecure=${TRAEFIK_API_INSECURE:-false}
      - --entrypoints.http.address=:${TRAEFIK_HTTP_PORT:-80}
      - --entrypoints.metrics.address=:9096
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addRoutersLabels=true
      - --metrics.prometheus.addServicesLabels=true
      - --metrics.prometheus.entryPoint=metrics
      - --metrics.prometheus=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker=false
      - --providers.file.filename=/traefik_config/${TRAEFIK_PROTOCOL}/dynamic.yml
      - --providers.file.watch=true
    depends_on:
      - traefik-init
    environment:
      DOMAIN: ${DOMAIN:-localhost}
      GRAFANA_DOMAIN: ${GRAFANA_DOMAIN-}
      GRAFANA_PATH: ${GRAFANA_PATH-/}
      TRAEFIK_PROTOCOL: ${TRAEFIK_PROTOCOL-}
    expose:
      - 9096
      - ${TRAEFIK_HTTP_PORT:-80}
      - ${TRAEFIK_DASHBOARD_PORT:-8080}
    image: docker.io/traefik:${TRAEFIK_RELEASE:-v3.4}
    labels:
      container_tag: ${COMPOSE_PROJECT_NAME:-rocketchat}#traefik
    logging:
      driver: json-file
    ports:
      - ${TRAEFIK_HTTP_PORT:-80}:${TRAEFIK_HTTP_PORT:-80}
      - ${TRAEFIK_DASHBOARD_PORT:-8080}:8080
    restart: always
    volumes:
      - traefik_config:/traefik_config:Z

volumes:
  traefik_config:
    driver: local
